# Generated by Django 5.1.2 on 2025-08-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_productgallery_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
